# -*- coding: utf-8 -*-
"""SaksitJittasopee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hC1dPF5BQqpOjcwigWRhp5DRu-nLo5fx
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ColabNotebooks/KJN-ICT

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks/KJN-ICT/yolov5

!pip install -r requirements.txt

import torch
# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
#img = 'https://ultralytics.com/images/zidane.jpg'
#img = '/content/yolov5/data/images/bus.jpg'
img = '/content/drive/MyDrive/Colab Notebooks/KJN-ICT/yolov5/2-2-2-3foodgroups_fruits_detailfeature.jpg'

# Inference
results = model(img)

# Results
results.print()
results.save()

#results.xyxy[0]
results.pandas().xyxy[0]

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks/KJN-ICT/dataset

!mkdir vehicles_open_image

# Commented out IPython magic to ensure Python compatibility.
# %cd vehicles_open_image

!curl -L "https://public.roboflow.com/ds/2Tb6yXY8l8?key=Eg82WpxUEr" > vehicles.zip

!unzip vehicles.zip

!rm vehicles.zip

import yaml
config = {'path': '/content/drive/MyDrive/Colab Notebooks/KJN-ICT/dataset/vehicles_open_image',
'train': '/content/drive/MyDrive/Colab Notebooks/KJN-ICT/dataset/vehicles_open_image/train',
'val': '/content/drive/MyDrive/Colab Notebooks/KJN-ICT/dataset/vehicles_open_image/valid',
'nc': 1,
'names': ['watermelon']}

with open("data.yaml", "w") as file:
  yaml.dump(config, file, default_flow_style=False)

lr0: 0.01 # initial learning rate (SGD=1E-2, Adam=1E-3)
lrf: 0.01 # final OneCycleLR learning rate (lr0 * lrf)
momentum: 0.937 # SGD momentum/Adam beta1
weight_decay: 0.0005 # optimizer weight decay 5e-4
warmup_epochs: 3.0 # warmup epochs (fractions ok)
warmup_momentum: 0.8 # warmup initial momentum
warmup_bias_lr: 0.1 # warmup initial bias lr
box: 0.05 # box loss gain
cls: 0.5 # cls loss gain
cls_pw: 1.0 # cls BCELoss positive_weight
obj: 1.0 # obj loss gain (scale with pixels)
obj_pw: 1.0 # obj BCELoss positive_weight
iou_t: 0.20 # IoU training threshold
anchor_t: 4.0 # anchor-multiple threshold
# anchors: 3 # anchors per output layer (0 to ignore)
fl_gamma: 0.0 # focal loss gamma (efficientDet default gamma=1.5)
hsv_h: 0.015 # image HSV-Hue augmentation (fraction)
hsv_s: 0.7 # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4 # image HSV-Value augmentation (fraction)
degrees: 0.0 # image rotation (+/- deg)
translate: 0.1 # image translation (+/- fraction)
scale: 0.5 # image scale (+/- gain)
shear: 0.0 # image shear (+/- deg)
perspective: 0.0 # image perspective (+/- fraction), range 0-0.001
flipud: 0.0 # image flip up-down (probability)
fliplr: 0.5 # image flip left-right (probability)
mosaic: 1.0 # image mosaic (probability)
mixup: 0.0 # image mixup (probability)
copy_paste: 0.0 # segment copy-paste (probability)

SIZE = 640
BATCH_SIZE = 16
EPOCHS = 10
MODEL = "yolov5s"
WORKERS = 1
PROJECT = "vehicles_open_image_pyimagesearch"
RUN_NAME = f"{MODEL}_size{SIZE}_epochs{EPOCHS}_batch{BATCH_SIZE}_small"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks/KJN-ICT/yolov5/
!python train.py --img {SIZE}\
--batch {BATCH_SIZE}\
--epochs {EPOCHS}\
--data '/content/drive/MyDrive/Colab Notebooks/KJN-ICT/dataset/vehicles_open_image/data.yaml'\
--weights {MODEL}.pt\
--workers {WORKERS}\
--project {PROJECT}\
--name {RUN_NAME}\
--exist-ok

!python detect.py --source '/content/drive/MyDrive/Colab Notebooks/KJN-ICT/dataset/vehicles_open_image/train/images' --weights '/content/drive/MyDrive/Colab Notebooks/KJN-ICT/yolov5/vehicles_open_image_pyimagesearch/yolov5s_size640_epochs10_batch16_small/weights/last.pt' --conf 0.5 --iou 0.45 --augment --project 'run_vehicles' --name 'detect_test' --save-txt --save-crop